# Generated by Django 3.1.2 on 2020-10-29 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 21, 5, 37, 654471, tzinfo=utc), verbose_name='birth date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+5493512345543', max_length=128, region=None, verbose_name='phone humber'),
            preserve_default=False,
        ),
    ]
