# Generated by Django 3.1.2 on 2020-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(0, 'Superuser'), (1, 'Supervisor'), (2, 'Abm')], primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='core.Role'),
        ),
    ]
